name: cfug_translator_bot
description:
version: 0.0.4

publish_to: none

environment:
  sdk: '>=3.10.0 <3.11.0'

dependencies:
  args: 2.7.0
  uuid: 4.5.2
  github: 9.25.0
  http: 1.6.0
  google_generative_ai: 0.4.7

dev_dependencies:
  lints: any
  test: any